### ISSUE TITLE
on Install, the repo is no longer signed

### ISSUE THREAD

**Issue by paulmac57** [wanduow/wandio#50]
Failed to fetch https://dl.bintray.com/wand/general/dists/bionic/InRelease  403  Forbidden [IP: 52.35.165.140 443]
E: The repository 'https://dl.bintray.com/wand/general bionic InRelease' is no longer signed

Hi, how can i fix this ? many thanks in advance

**Comment by paulmac57** [comment]
Nevermind, I just simply removed the file in  sources.d. Sorry to bother you.

**Comment by rsanger** [comment]
For anyone else who encounters this issue.
Bintray has shutdown and we've replaced it with Cloudsmith.
Details on how to install from Cloudsmith are in the updated install guide here: https://github.com/wanduow/wandio/wiki/Installing-via-Debian-Package
