### ISSUE TITLE
bug reading bzip2 files

### ISSUE THREAD

**Issue by herrin** [wanduow/wandio#54]
bz_read() in lib/ior-bzip.c assumes that BZ_STREAM_END is EOF. That is not correct. It's the end of a one bzip2 stream. A bzip2 file can consist of more than one concatenated stream.

See https://stackoverflow.com/questions/35330911/how-to-decompress-pbzip2-data-in-memory-buffer-by-using-libbz2-library-in-c

As a result of this bug, wandio truncates files compressed with pbzip2.

**Comment by salcock** [comment]
This issue is resolved in the 4.2.6 release that was published today.
