### ISSUE TITLE
4.2.6 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [wanduow/wandio#55]
👋 it looks like the 4.2.6 release was not completed, ie the release notes did not make to github release. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/143901

**Comment by salcock** [comment]
Done, thanks for pointing this out :+1:

**Comment by chenrui333** [comment]
@salcock thanks for the quick turnaround!
